AWSTemplateFormatVersion: '2010-09-09'
Description: Athena infrastructure for analytics queries

Parameters:
  QueryResultsBucket:
    Type: String
    Description: S3 bucket to store Athena query results (format: s3://bucket-name)

Resources:
  AthenaWorkGroup:
    Type: AWS::Athena::WorkGroup
    Properties:
      Name: "MyCompanyAthenaWorkGroup"
      WorkGroupConfiguration:
        EnforceWorkGroupConfiguration: true
        PublishCloudWatchMetricsEnabled: true
        ResultConfiguration:
          OutputLocation: !Ref QueryResultsBucket

Outputs:
  AthenaWorkGroupName:
    Value: "MyCompanyAthenaWorkGroup"
